### ISSUE TITLE
How to display the name of a universalpay ?

### ISSUE THREAD

**Issue by AlainRnet** [prestalab/universalpay#15]
Hello.
In orders' display, the name of a universal payment appears. While the PDFs and the orders themselves, it is the name of the module that appears.
I think it's important that the name of the universal payment appears and not the module's name.

How can I do this?

I see that the information is in the field payment of ps_orders table
How to call this field in smarty and/or PHP?

Can you tell me what file I have to change?

Thank you in advance for your answer.
Best regards.

**Comment by AlainRnet** [comment]
In PDF invoice, file invoice.payment-tab.tpl, I see "{$order->payment}" but it doesn't display the name of universalpay ?!?

**Comment by prestalab** [comment]
Switch to Force recompile smarty templates in Performance admin tab
