### ISSUE TITLE
no paiment on Checkout

### ISSUE THREAD

**Issue by AlainRnet** [prestalab/universalpay#16]
Hi!
I create 2 payment systems and select all carriers'options but no payment systems can be selected :(
I installed last week UniversalPaySystem v2.3.1 on PS 1.6.1.5

How/where to download a previous version ?

**Comment by AlainRnet** [comment]
Sorry, it was a bad config. I had to recreate pay.sys. and it contains mistakes.
Everything's all right for this point.

**Comment by AlainRnet** [comment]
OK, I compare 2 differents versions and I notice that in 2.3.1 it's not possible to select customer type, so no payment system is shown...

**Comment by prestalab** [comment]
Fixed in master version
