### ISSUE TITLE
Prestashop 1.7 support

### ISSUE THREAD

**Issue by sarment0** [prestalab/universalpay#24]
Hi, are you planing to support prestashop 1.7?

**Comment by tank-crd** [comment]
I would also be very interested in support for this module. I would like to help. If I could donate to help further it's process and open up for PS 1.7, I would.

**Comment by tehnoinstyle** [comment]
Hi, module support prestashop 1.7.2.4?
Thanks.

**Comment by imivz** [comment]
Needs support for 1.7.3!

**Comment by saudis79** [comment]
Hi, Can anyone confirm that there will be support for Prestashop 1.7.3?

**Comment by ghost** [comment]
i install in ps 1.7.4.2 and not work. The new tab return one error when do click:
Oops! An Error Occurred
The server returned a "500 Internal Server Error".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.
(i try 2 times)

**Comment by prestalab** [comment]
Added support for 1.7.1-1.7.x
